@hostname=localhost
@port=3000
@baseUrl={{hostname}}:{{port}}

### Health check endpoint
GET http://{{baseUrl}}/ping HTTP/1.1

### Get all users
GET http://{{baseUrl}}/users HTTP/1.1

### Create a new user
POST http://{{baseUrl}}/users HTTP/1.1
Content-Type: application/json

{
    "name": "test",
    "email": "test@email.com"
}

### Update a exiting User
PUT http://{{baseUrl}}/users/691c75d15e45304d3a197590 HTTP/1.1
Content-Type: application/json

{
    "email": "test@test.com"
}