### Health check endpoint
GET http://localhost:3000/ping HTTP/1.1

### Get all users
GET http://localhost:3000/users?limit=10 HTTP/1.1

### Create a new user
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "name": "test",
    "email": "test@email.com"
}