@hostname=localhost
@port=3000
@baseUrl={{hostname}}:{{port}}

### Health check endpoint
GET http://{{baseUrl}}/ping HTTP/1.1

### Get all users
GET http://{{baseUrl}}/users HTTP/1.1

### Create a new user
POST http://{{baseUrl}}/users HTTP/1.1
Content-Type: application/json

{
    "name": "test",
    "email": "test@email.com"
}

@userId=691f0a38e903f37c1aada043

### Get Single users
GET http://{{baseUrl}}/users/{{userId}} HTTP/1.1

### Delete a exiting User
DELETE  http://{{baseUrl}}/users/{{userId}} HTTP/1.1

### Update a exiting User
PUT http://{{baseUrl}}/users/{{userId}} HTTP/1.1
Content-Type: application/json

{
    "email": "test@test.com"
}